<meta name="DC.title" content="The National Archives Learning Curve | Power, Politics and Protest |  The Chartists" />
<meta name="DC.subject" content="Britain, political, reform, politics, nineteenth, 19th, century, rights, democracy, democratic, voting, constituency, election, MP, voter, vote, parliament, primary, source, protest, riot, disturbance, Chartism, Chartist, movement, revolution, Preston, charter, union" />
<meta name="keywords" content="Britain, political, reform, politics, nineteenth, 19th, century, rights, democracy, democratic, voting, constituency, election, MP, voter, vote, parliament, primary, source, protest, riot, disturbance, Chartism, Chartist, movement, revolution, Preston, charter, union">
<meta name="DCTERMS.temporal" content="1835-1850" />
<meta name="DC.description" content="This gallery explores what Chartism was all about and whether the riot at Preston was a Chartist uprising">
<meta name="description" content="This gallery explores what Chartism was all about and whether the riot at Preston was a Chartist uprising">
