<meta name="DC.title" content="The National Archives Learning Curve | Power, Politics and Protest |  Captain Swing" />
<meta name="DC.subject" content="Britain, political, reform, politics, nineteenth, 19th, century, rights, democracy, democratic, voting, constituency, election, MP, voter, vote, parliament, primary, source, Captain Swing, agriculture, agricultural, rural, labourer, riot, disturbance, threshing, machines, protest, country, countryside" />
<meta name="keywords" content="Britain, political, reform, politics, nineteenth, 19th, century, rights, democracy, democratic, voting, constituency, election, MP, voter, vote, parliament, primary, source, Captain Swing, agriculture, agricultural, rural, labourer, riot, disturbance, threshing, machines, protest, country, countryside"/>
<meta name="DCTERMS.temporal" content="1820-1835" />
<meta name="DC.description" content="This gallery explores how the agricultural labourers of the 1830s tried to protect their jobs"/>
<meta name="description" content="This gallery explores how the agricultural labourers of the 1830s tried to protect their jobs"/>

