<meta name="DC.title" content="The National Archives Learning Curve | Power, Politics and Protest |  The Great Reform Act" />
<meta name="DC.subject" content="Britain, political, reform, politics, nineteenth, 19th, century, rights, democracy, democratic, voting, constituency, election, MP, voter, vote, parliament, primary, source, protest, great reform act, 1832, change, union, unions, riot, disturbance, Bristol, Sir Charles Weatherall" />
<meta name="keywords" content="Britain, political, reform, politics, nineteenth, 19th, century, rights, democracy, democratic, voting, constituency, election, MP, voter, vote, parliament, primary, source, protest, great reform act, 1832, change, union, unions, riot, disturbance, Bristol, Sir Charles Weatherall"/>
<meta name="DCTERMS.temporal" content="1820-1835" />
<meta name="DC.description" content="This gallery explores how the government changed the political system with the Great Reform Act of 1832"/>
<meta name="description" content="This gallery explores how the government changed the political system with the Great Reform Act of 1832"/>

