<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="100%" align="left" valign="top"><img src="/education/politics/images/pixels/hextrans.gif" alt="" width="1" height="2" border="0" /></td>	
  </tr>
  <tr>
    <td width="100%" align="left" valign="top" bgcolor="#000000"><img src="/education/politics/images/pixels/hextrans.gif" alt="" width="1" height="1" border="0" /></td>	
  </tr>   
  <tr>
    <td width="100%" align="left" valign="top" class="bg_arrows"><img src="/education/politics/images/pixels/hextrans.gif" alt="" width="1" height="13" border="0" /></td>	
  </tr> 
</table>