<meta name="DC.title" content="The National Archives Learning Curve | Power, Politics and Protest |  Peterloo" />
<meta name="DC.subject" content="Britain, political, reform, politics, nineteenth, 19th, century, rights, democracy, democratic, voting, constituency, election, MP, voter, vote, parliament, primary, source, disturbance, Peterloo, St Peter’s Field, Henry Hunt, Manchester, law, laws" />
<meta name="keywords" content="Britain, political, reform, politics, nineteenth, 19th, century, rights, democracy, democratic, voting, constituency, election, MP, voter, vote, parliament, primary, source, disturbance, Peterloo, St Peter’s Field, Henry Hunt, Manchester, law, laws"/>
<meta name="DCTERMS.temporal" content="1815-1825" />
<meta name="DC.description" content="This gallery explores what happened at St Peter’s Field, Manchester in 1819 (known as Peterloo) and whose fault it was"/>
<meta name="description" content="This gallery explores what happened at St Peter’s Field, Manchester in 1819 (known as Peterloo) and whose fault it was"/>
