<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="5" height="8" align="left" valign="top" class="border_high"><img src="/education/politics/images/pixels/hextrans.gif" alt="" width="5" height="8"/education/></td>
  </tr>
</table>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="10" align="left" valign="top" class="bg_cream"><img src="/education/politics/images/pixels/hextrans.gif" alt="" width="10" height="10"/education/></td>
    <td width="100%" align="left" valign="top" class="bg_cream"><img src="/education/politics/images/labels/label_lc.gif" alt="Learning Curve" width="116" height="18" border="0"/education/></td>	
  </tr>
</table>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="100%" align="center" valign="top" class="bg_cream"><img src="/education/politics/images/pixels/hextrans.gif" alt="" width="1" height="10" border="0"/education/></td>	
  </tr>
  <tr>
    <td width="100%" align="center" valign="top" class="bg_cream"><img src="/education/politics/images/labels/label_ppp.gif" alt="Power, Politics and Protest" width="433" height="16" border="0"/education/></td>	
  </tr>
  <tr>
    <td width="100%" align="left" valign="top" class="bg_cream"><img src="/education/politics/images/pixels/hextrans.gif" alt="" width="1" height="3" border="0"/education/></td>	
  </tr>
  <tr>
    <td width="100%" align="left" valign="top" bgcolor="#000000"><img src="/education/politics/images/pixels/hextrans.gif" alt="" width="1" height="1" border="0"/education/></td>	
  </tr>  
    <tr>
    <td width="100%" align="left" valign="top" class="bg_cream"><img src="/education/politics/images/pixels/hextrans.gif" alt="" width="1" height="2" border="0"/education/></td>	
  </tr>
  <tr>
    <td width="100%" align="left" valign="top" bgcolor="#000000"><img src="/education/politics/images/pixels/hextrans.gif" alt="" width="1" height="1" border="0"/education/></td>	
  </tr> 
    <tr>
    <td width="100%" align="left" valign="top" class="bg_cream"><img src="/education/politics/images/pixels/hextrans.gif" alt="" width="1" height="7" border="0"/education/></td>	
  </tr>
  <tr>
    <td width="100%" align="center" valign="top" class="bg_cream"><img src="/education/politics/images/labels/label_the_growth.gif" alt="The growth of political rights in Britain in the 19th century" width="694" height="10" border="0"/education/></td>	
  </tr> 
    <tr>
    <td width="100%" align="left" valign="top" class="bg_cream"><img src="/education/politics/images/pixels/hextrans.gif" alt="" width="1" height="7" border="0"/education/></td>	
  </tr>      
</table>